In [1]:
import pandas as pd
import os
from get_repo_name import get_repo_name

repo_name = get_repo_name ( os.path.basename ( os.getcwd() ) )
dataset_path = f'datasets/{repo_name}_modfiles.csv'
df = pd.read_csv (dataset_path)
df.head()

,commit_hash,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,2636f3c62f1a407b2996da6e3fe6fdc5d1ccd764,Chetan Kaushik,dynamitechetan@gmail.com,2016-07-16 15:02:01+05:18,False,NaN,NaN,NaN,README.md,ModificationType.ADD,2,0,NaN,NaN,NaN
1,e58c46237bdb8949bf063b6ec399ba24cec16eba,Anup Kumar Panwar,mylnext@gmail.com,2016-07-16 16:19:51+05:18,False,NaN,NaN,NaN,BubbleSort.python,ModificationType.ADD,26,0,NaN,NaN,NaN
2,5e3a0d49d0544f5cc98212e1130ab01ee21b135e,Anup Kumar Panwar,mylnext@gmail.com,2016-07-19 12:22:43+05:18,False,NaN,NaN,NaN,InsertionSort.python,ModificationType.ADD,27,0,NaN,NaN,NaN
3,b1b4bdaecddde492a9cca441b9c236ba16ee1d01,Chetan Kaushik,dynamitechetan@gmail.com,2016-07-19 22:22:17+05:18,False,1.0,1.0,0.636364,BubbleSort.py,ModificationType.RENAME,0,0,NaN,NaN,NaN
4,b1b4bdaecddde492a9cca441b9c236ba16ee1d01,Chetan Kaushik,dynamitechetan@gmail.com,2016-07-19 22:22:17+05:18,False,1.0,1.0,0.636364,InsertionSort.py,ModificationType.RENAME,0,2,15.0,0.0,119.0

In [2]:
df.insert ( 1, 'year_month', pd.to_datetime(df['commit_datetime'], utc=True).dt.to_period('M') )
df

G:\Anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:1101: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  warnings.warn(

,commit_hash,year_month,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,2636f3c62f1a407b2996da6e3fe6fdc5d1ccd764,2016-07,Chetan Kaushik,dynamitechetan@gmail.com,2016-07-16 15:02:01+05:18,False,NaN,NaN,NaN,README.md,ModificationType.ADD,2,0,NaN,NaN,NaN
1,e58c46237bdb8949bf063b6ec399ba24cec16eba,2016-07,Anup Kumar Panwar,mylnext@gmail.com,2016-07-16 16:19:51+05:18,False,NaN,NaN,NaN,BubbleSort.python,ModificationType.ADD,26,0,NaN,NaN,NaN
2,5e3a0d49d0544f5cc98212e1130ab01ee21b135e,2016-07,Anup Kumar Panwar,mylnext@gmail.com,2016-07-19 12:22:43+05:18,False,NaN,NaN,NaN,InsertionSort.python,ModificationType.ADD,27,0,NaN,NaN,NaN
3,b1b4bdaecddde492a9cca441b9c236ba16ee1d01,2016-07,Chetan Kaushik,dynamitechetan@gmail.com,2016-07-19 22:22:17+05:18,False,1.000000,1.0,0.636364,BubbleSort.py,ModificationType.RENAME,0,0,NaN,NaN,NaN
4,b1b4bdaecddde492a9cca441b9c236ba16ee1d01,2016-07,Chetan Kaushik,dynamitechetan@gmail.com,2016-07-19 22:22:17+05:18,False,1.000000,1.0,0.636364,InsertionSort.py,ModificationType.RENAME,0,2,15.0,0.0,119.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6232,97f25d4b431ffe432a30853ed0bcc75ea5e8166f,2022-07,Maxim Smolskiy,mithridatus@mail.ru,2022-07-26 21:33:14+05:18,False,0.270833,1.0,1.000000,DIRECTORY.md,ModificationType.MODIFY,2,0,NaN,NaN,NaN
6233,97f25d4b431ffe432a30853ed0bcc75ea5e8166f,2022-07,Maxim Smolskiy,mithridatus@mail.ru,2022-07-26 21:33:14+05:18,False,0.270833,1.0,1.000000,__init__.py,ModificationType.ADD,0,0,NaN,NaN,NaN
6234,97f25d4b431ffe432a30853ed0bcc75ea5e8166f,2022-07,Maxim Smolskiy,mithridatus@mail.ru,2022-07-26 21:33:14+05:18,False,0.270833,1.0,1.000000,sol1.py,ModificationType.ADD,94,0,78.0,5.0,184.0
6235,defc205ef4459264b753429c6cbc23481347e8b7,2022-08,Maxim Smolskiy,mithridatus@mail.ru,2022-08-06 19:22:24+05:18,False,0.982456,1.0,0.000000,sol1.py,ModificationType.MODIFY,21,91,106.0,9.0,206.0
6236,9eac958725c8e5c62b225c77eaf83ec0ecb7e6f6,2022-08,Horst JENS,horstjens@gmail.com,2022-08-06 17:47:56+02:00,False,NaN,NaN,NaN,horizontal_projectile_motion.py,ModificationType.MODIFY,1,1,122.0,10.0,336.0

In [3]:
grouped_df = df.groupby(['year_month']).agg({
    
    'commit_hash': 'nunique', 
    'file_lines_added': 'sum', 
    'file_lines_deleted': 'sum',
    'file_loc': 'sum',
    'file_complexity': 'sum',
    'file_token_count': 'sum',
    'dmm_unit_size': 'mean',
    'dmm_unit_complexity': 'mean',
    'dmm_unit_interfacing': 'mean'
} ).reset_index(level=[0])


grouped_df.rename(columns = {
    'commit_hash': 'commit_count',
    'file_lines_added': 'additions',
    'file_lines_deleted': 'deletions',
    'file_loc': 'agg_loc',
    'file_complexity': 'agg_complexity',
    'file_token_count': 'agg_token_count',
}, inplace = True)

grouped_df

,year_month,commit_count,additions,deletions,agg_loc,agg_complexity,agg_token_count,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing
0,2016-07,23,845,284,803.0,186.0,4815.0,0.656250,0.843750,0.887784
1,2016-08,42,54049,476,1727.0,371.0,9842.0,0.497393,0.444129,0.703988
2,2016-09,14,236406,53,1046.0,205.0,6446.0,0.665110,0.867870,0.881715
3,2016-10,14,266,32,504.0,109.0,2807.0,0.923077,0.769231,0.760725
4,2016-11,5,137,21,153.0,47.0,965.0,1.000000,0.666667,1.000000
...,...,...,...,...,...,...,...,...,...,...
67,2022-04,4,347,67,755.0,79.0,2113.0,0.070175,0.957895,0.833333
68,2022-05,21,1275,252,3757.0,509.0,14436.0,0.500589,0.685755,0.815789
69,2022-06,7,1396,887,570.0,88.0,2422.0,0.194859,0.427192,0.650912
70,2022-07,18,812,224,10375.0,1664.0,45629.0,0.562689,0.422222,0.552161
71,2022-08,2,22,92,228.0,19.0,542.0,0.982456,1.000000,0.000000

In [4]:
grouped_df.to_csv ( f'datasets/{repo_name}_groupedby_yearmonth.csv', index = False )