In [1]:
import pandas as pd
import os
from get_repo_name import get_repo_name
from glob import glob
from shutil import copy

results_path = './results/'
cat_datasets = 'top_repos_by_star_count_datasets'
dst = results_path + cat_datasets + '/'

if cat_datasets not in os.listdir(results_path):
    os.mkdir ( dst )

cat_path = './top_repos/top_repos_by_star_count/'

for repo in os.listdir(cat_path):

    repo_name = get_repo_name ( os.path.basename ( repo ) )
    datasets_path = '/datasets/'
    csv_file = f'{ repo_name }_modfiles.csv'
    if csv_file in os.listdir ( cat_path + repo + datasets_path ):
        src = cat_path + repo + datasets_path + csv_file
        copy ( src, dst )

In [2]:
glob_path = os.path.join ( dst, "*_modfiles.csv" )
master_dataset = glob ( glob_path )

df = pd.concat ( map ( pd.read_csv, master_dataset ), ignore_index = True )
df

,commit_hash,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,f57407db93b2bbcf15b59af10e6f689ca8443372,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 15:31:43+08:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,2,0,NaN,NaN,NaN
1,80eb8ea2e4462e7c0f83b071545e9b01bcf0e63c,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 17:47:17+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,2,0,NaN,NaN,NaN
2,87de776ac2c22174cbb3a554e89a0ff2a1fadcc5,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 18:08:38+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,22,0,NaN,NaN,NaN
3,51881babca2db8a8ef8c066f134216218deada0d,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 18:10:21+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,0,19,NaN,NaN,NaN
4,e85dda6f6303f60c3ff9a763e0de3ca91fe81009,calvin325,calvin325@gmail.com,2019-03-26 23:29:39+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385541,6668deaa8a6f45c31e5eaf308d92b858fdbf4261,Kyle Simpson,getify@gmail.com,2022-08-04 00:07:03-05:00,False,NaN,NaN,NaN,ch1.md,ModificationType.MODIFY,25,2,NaN,NaN,NaN
385542,6668deaa8a6f45c31e5eaf308d92b858fdbf4261,Kyle Simpson,getify@gmail.com,2022-08-04 00:07:03-05:00,False,NaN,NaN,NaN,ch2.md,ModificationType.MODIFY,39,16,NaN,NaN,NaN
385543,2cb92444a613004fd09a6696a6810f3986a01242,Kyle Simpson,getify@gmail.com,2022-08-05 12:13:18-05:00,False,NaN,NaN,NaN,ch1.md,ModificationType.MODIFY,5,75,NaN,NaN,NaN
385544,2cb92444a613004fd09a6696a6810f3986a01242,Kyle Simpson,getify@gmail.com,2022-08-05 12:13:18-05:00,False,NaN,NaN,NaN,ch2.md,ModificationType.MODIFY,192,5,NaN,NaN,NaN
385545,0a5ffd75f6d5593d55b467e2962daa95a5b8d946,Kyle Simpson,getify@gmail.com,2022-08-06 11:27:48-05:00,False,NaN,NaN,NaN,ch2.md,ModificationType.MODIFY,143,5,NaN,NaN,NaN

In [3]:
df.insert ( 1, 'year_month', pd.to_datetime(df['commit_datetime'], utc = True).dt.to_period('M') )
df

G:\Anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:1101: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  warnings.warn(

,commit_hash,year_month,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,f57407db93b2bbcf15b59af10e6f689ca8443372,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 15:31:43+08:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,2,0,NaN,NaN,NaN
1,80eb8ea2e4462e7c0f83b071545e9b01bcf0e63c,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 17:47:17+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,2,0,NaN,NaN,NaN
2,87de776ac2c22174cbb3a554e89a0ff2a1fadcc5,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 18:08:38+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,22,0,NaN,NaN,NaN
3,51881babca2db8a8ef8c066f134216218deada0d,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 18:10:21+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,0,19,NaN,NaN,NaN
4,e85dda6f6303f60c3ff9a763e0de3ca91fe81009,2019-03,calvin325,calvin325@gmail.com,2019-03-26 23:29:39+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385541,6668deaa8a6f45c31e5eaf308d92b858fdbf4261,2022-08,Kyle Simpson,getify@gmail.com,2022-08-04 00:07:03-05:00,False,NaN,NaN,NaN,ch1.md,ModificationType.MODIFY,25,2,NaN,NaN,NaN
385542,6668deaa8a6f45c31e5eaf308d92b858fdbf4261,2022-08,Kyle Simpson,getify@gmail.com,2022-08-04 00:07:03-05:00,False,NaN,NaN,NaN,ch2.md,ModificationType.MODIFY,39,16,NaN,NaN,NaN
385543,2cb92444a613004fd09a6696a6810f3986a01242,2022-08,Kyle Simpson,getify@gmail.com,2022-08-05 12:13:18-05:00,False,NaN,NaN,NaN,ch1.md,ModificationType.MODIFY,5,75,NaN,NaN,NaN
385544,2cb92444a613004fd09a6696a6810f3986a01242,2022-08,Kyle Simpson,getify@gmail.com,2022-08-05 12:13:18-05:00,False,NaN,NaN,NaN,ch2.md,ModificationType.MODIFY,192,5,NaN,NaN,NaN
385545,0a5ffd75f6d5593d55b467e2962daa95a5b8d946,2022-08,Kyle Simpson,getify@gmail.com,2022-08-06 11:27:48-05:00,False,NaN,NaN,NaN,ch2.md,ModificationType.MODIFY,143,5,NaN,NaN,NaN

In [4]:
from analysis_lib import year_pre_covid_ym, pre_covid_ym, covid_ym, year_post_covid_ym

df.drop ( df[df.year_month < year_pre_covid_ym].index, inplace = True )
df.drop ( df[df.year_month > year_post_covid_ym].index, inplace = True )
df.reset_index ( drop = True, inplace = True )
df

,commit_hash,year_month,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,f57407db93b2bbcf15b59af10e6f689ca8443372,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 15:31:43+08:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,2,0,NaN,NaN,NaN
1,80eb8ea2e4462e7c0f83b071545e9b01bcf0e63c,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 17:47:17+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,2,0,NaN,NaN,NaN
2,87de776ac2c22174cbb3a554e89a0ff2a1fadcc5,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 18:08:38+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,22,0,NaN,NaN,NaN
3,51881babca2db8a8ef8c066f134216218deada0d,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 18:10:21+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,0,19,NaN,NaN,NaN
4,e85dda6f6303f60c3ff9a763e0de3ca91fe81009,2019-03,calvin325,calvin325@gmail.com,2019-03-26 23:29:39+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124230,8a1cc1170f0e87d61b1d7add2b57561bc37f74e2,2020-12,Kyle Simpson,getify@gmail.com,2020-12-11 11:10:37-06:00,False,NaN,NaN,NaN,ch3.md,ModificationType.MODIFY,1,0,NaN,NaN,NaN
124231,8a1cc1170f0e87d61b1d7add2b57561bc37f74e2,2020-12,Kyle Simpson,getify@gmail.com,2020-12-11 11:10:37-06:00,False,NaN,NaN,NaN,fig1.png,ModificationType.MODIFY,0,0,NaN,NaN,NaN
124232,8a1cc1170f0e87d61b1d7add2b57561bc37f74e2,2020-12,Kyle Simpson,getify@gmail.com,2020-12-11 11:10:37-06:00,False,NaN,NaN,NaN,fig3.png,ModificationType.MODIFY,0,0,NaN,NaN,NaN
124233,8861041133f496edce0d03885e2e998d50c3414a,2020-12,Kyle Simpson,getify@gmail.com,2020-12-30 11:33:35-06:00,False,NaN,NaN,NaN,ch1.md,ModificationType.MODIFY,3,3,NaN,NaN,NaN
124234,8861041133f496edce0d03885e2e998d50c3414a,2020-12,Kyle Simpson,getify@gmail.com,2020-12-30 11:33:35-06:00,False,NaN,NaN,NaN,ch3.md,ModificationType.MODIFY,3,3,NaN,NaN,NaN

In [5]:
from analysis_lib import generate_ordinal_encoding_map

enc_map = generate_ordinal_encoding_map ( df["commit_author_email"] )
df["commit_author_enc"] = df["commit_author_email"].replace(enc_map)
df.head()

,commit_hash,year_month,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count,commit_author_enc
0,f57407db93b2bbcf15b59af10e6f689ca8443372,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 15:31:43+08:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,2,0,NaN,NaN,NaN,1
1,80eb8ea2e4462e7c0f83b071545e9b01bcf0e63c,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 17:47:17+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,2,0,NaN,NaN,NaN,1
2,87de776ac2c22174cbb3a554e89a0ff2a1fadcc5,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 18:08:38+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,22,0,NaN,NaN,NaN,1
3,51881babca2db8a8ef8c066f134216218deada0d,2019-03,996icu,48942249+996icu@users.noreply.github.com,2019-03-26 18:10:21+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,0,19,NaN,NaN,NaN,1
4,e85dda6f6303f60c3ff9a763e0de3ca91fe81009,2019-03,calvin325,calvin325@gmail.com,2019-03-26 23:29:39+08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN,2

In [6]:
df [ df['commit_author_enc'] == 0 ].shape[0] # check if any invalid author code is present

0

In [7]:
pre_df = df[df.year_month <= pre_covid_ym ]
pre_df.year_month.min(), pre_df.year_month.max()

(Period('2019-03', 'M'), Period('2020-02', 'M'))

In [8]:
post_df = df[df.year_month >= covid_ym ]
post_df.year_month.min(), post_df.year_month.max()

(Period('2020-03', 'M'), Period('2021-02', 'M'))

In [9]:
grouped_pre_df = pre_df.groupby(['commit_author_enc']).agg({
    
    'commit_hash': 'nunique', 
    'file_lines_added': 'sum', 
    'file_lines_deleted': 'sum',
    'file_loc': 'sum',
    'file_complexity': 'sum',
    'file_token_count': 'sum'
} ).reset_index(level=[0])


grouped_pre_df.rename(columns = {
    'commit_hash': 'commit_count',
    'file_lines_added': 'additions',
    'file_lines_deleted': 'deletions',
    'file_loc': 'agg_loc',
    'file_complexity': 'agg_complexity',
    'file_token_count': 'agg_token_count'
}, inplace = True)

grouped_pre_df

,commit_author_enc,commit_count,additions,deletions,agg_loc,agg_complexity,agg_token_count
0,1,147,497,533,0.0,0.0,0.0
1,2,1,1,1,0.0,0.0,0.0
2,3,1,1,1,0.0,0.0,0.0
3,4,1,11,11,0.0,0.0,0.0
4,5,2,15,6,0.0,0.0,0.0
...,...,...,...,...,...,...,...
2406,4195,1,1,1,0.0,0.0,0.0
2407,4196,1,1,1,0.0,0.0,0.0
2408,4197,1,165,165,0.0,0.0,0.0
2409,4198,1,1,1,0.0,0.0,0.0
2410,4199,1,1,1,0.0,0.0,0.0

In [10]:
grouped_post_df = post_df.groupby(['commit_author_enc']).agg({
    
    'commit_hash': 'nunique', 
    'file_lines_added': 'sum', 
    'file_lines_deleted': 'sum',
    'file_loc': 'sum',
    'file_complexity': 'sum',
    'file_token_count': 'sum'
} ).reset_index(level=[0])


grouped_post_df.rename(columns = {
    'commit_hash': 'commit_count',
    'file_lines_added': 'additions',
    'file_lines_deleted': 'deletions',
    'file_loc': 'agg_loc',
    'file_complexity': 'agg_complexity',
    'file_token_count': 'agg_token_count'
}, inplace = True)

grouped_post_df

,commit_author_enc,commit_count,additions,deletions,agg_loc,agg_complexity,agg_token_count
0,38,2,234,28,0.0,0.0,0.0
1,62,1,2,0,0.0,0.0,0.0
2,409,1,1,1,0.0,0.0,0.0
3,497,1,37,4,0.0,0.0,0.0
4,708,3,2,1,0.0,0.0,0.0
...,...,...,...,...,...,...,...
2023,4201,1,1,1,0.0,0.0,0.0
2024,4202,1,1,1,0.0,0.0,0.0
2025,4203,1,1,1,0.0,0.0,0.0
2026,4204,1,1,1,0.0,0.0,0.0
2027,4205,1,3,3,0.0,0.0,0.0

In [11]:
from analysis_lib import calc_and_compare_means

calc_and_compare_means ( grouped_pre_df, grouped_post_df )

Pre and Post-Covid Mean Comparisons:
commit count :  5  vs  5  ->  No change
additions :  600  vs  590  ->  Down (1.7%)
deletions :  390  vs  346  ->  Down (11.3%)
agg loc :  1858  vs  2364  ->  Up (27.2%)
agg complexity :  224  vs  235  ->  Up (4.9%)
agg token count :  9381  vs  11109  ->  Up (18.4%)

In [12]:
from analysis_lib import get_equilibrium_pc

print("Pre-pandemic equilibrium percentages:")
for idx in range ( 1, 7 ):
    print ( f'{grouped_pre_df.columns[idx]} = { get_equilibrium_pc ( list ( grouped_pre_df[grouped_pre_df.columns[idx]] ) ) }' )
    
print("\nPost-pandemic equilibrium percentages:")
for idx in range ( 1, 7 ):
    print ( f'{grouped_post_df.columns[idx]} = { get_equilibrium_pc ( list ( grouped_post_df[grouped_post_df.columns[idx]] ) ) }' )

Pre-pandemic equilibrium percentages:
commit_count = 1.0
additions = 0.5
deletions = 0.3
agg_loc = 0.2
agg_complexity = 0.2
agg_token_count = 0.2

Post-pandemic equilibrium percentages:
commit_count = 1.5
additions = 0.7
deletions = 0.4
agg_loc = 0.1
agg_complexity = 0.2
agg_token_count = 0.2

In [13]:
from analysis_lib import get_pareto_pc

print("Pre-pandemic pareto percentages:")
for idx in range ( 1, 7 ):
    print ( f'{grouped_pre_df.columns[idx]} = { get_pareto_pc ( list ( grouped_pre_df[grouped_pre_df.columns[idx]] ) ) }' )
    
print("\nPost-pandemic pareto percentages:")
for idx in range ( 1, 7 ):
    print ( f'{grouped_post_df.columns[idx]} = { get_pareto_pc ( list ( grouped_post_df[grouped_post_df.columns[idx]] ) ) }' )

Pre-pandemic pareto percentages:
commit_count = 15.7
additions = 1.5
deletions = 1.1
agg_loc = 0.3
agg_complexity = 0.3
agg_token_count = 0.3

Post-pandemic pareto percentages:
commit_count = 14.4
additions = 2.4
deletions = 1.5
agg_loc = 0.4
agg_complexity = 0.5
agg_token_count = 0.4

In [20]:
pre_cpl = grouped_pre_df.agg_complexity.sum()/grouped_pre_df.agg_loc.sum()
post_cpl = grouped_post_df.agg_complexity.sum()/grouped_post_df.agg_loc.sum()
change_perc = (post_cpl - pre_cpl) / 100
change_perc

-0.00021419390580309768