In [1]:
import pandas as pd
import os
from get_repo_name import get_repo_name

repo_name = get_repo_name ( os.path.basename ( os.getcwd() ) )
dataset_path = f'datasets/{repo_name}_modfiles.csv'
df = pd.read_csv (dataset_path)
df.head()

,commit_hash,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,976d90f37fc2a87eff4fba93db2db30788f67d83,Donne Martin,donne.martin@gmail.com,2017-02-26 05:08:55-08:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,1,0,NaN,NaN,NaN
1,ee6227a2a558281b37fe23ef1c627d5f95c331a6,Donne Martin,donne.martin@gmail.com,2017-02-26 05:09:37-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,5,0,NaN,NaN,NaN
2,0782047336cccd731281abe7605d5bf95496dadb,Donne Martin,donne.martin@gmail.com,2017-02-26 05:14:10-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,28,0,NaN,NaN,NaN
3,35f22bb85a40a94c657824919255ef13d25b7168,Donne Martin,donne.martin@gmail.com,2017-02-26 05:14:17-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,32,0,NaN,NaN,NaN
4,3bfedf4269c2c107a701d5dba8abe8f1d0d699d7,Donne Martin,donne.martin@gmail.com,2017-02-26 05:14:17-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,14,0,NaN,NaN,NaN

In [2]:
df.insert ( 1, 'year_month', pd.to_datetime(df['commit_datetime'], utc=True).dt.to_period('M') )
df

G:\Anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:1101: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  warnings.warn(

,commit_hash,year_month,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,976d90f37fc2a87eff4fba93db2db30788f67d83,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:08:55-08:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,1,0,NaN,NaN,NaN
1,ee6227a2a558281b37fe23ef1c627d5f95c331a6,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:09:37-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,5,0,NaN,NaN,NaN
2,0782047336cccd731281abe7605d5bf95496dadb,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:14:10-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,28,0,NaN,NaN,NaN
3,35f22bb85a40a94c657824919255ef13d25b7168,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:14:17-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,32,0,NaN,NaN,NaN
4,3bfedf4269c2c107a701d5dba8abe8f1d0d699d7,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:14:17-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,14,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,79364dbbdcc305cf411719d0ea53345b5048d53c,2022-04,mleers,mleers4@gmail.com,2022-04-19 20:37:02-04:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN
519,7a094cec63795a3ebbaacebdf9dc4294cd3179b2,2022-04,Kian-Meng Ang,kianmeng.ang@gmail.com,2022-04-23 09:14:45-04:00,False,NaN,NaN,NaN,CONTRIBUTING.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN
520,7a094cec63795a3ebbaacebdf9dc4294cd3179b2,2022-04,Kian-Meng Ang,kianmeng.ang@gmail.com,2022-04-23 09:14:45-04:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN
521,7a094cec63795a3ebbaacebdf9dc4294cd3179b2,2022-04,Kian-Meng Ang,kianmeng.ang@gmail.com,2022-04-23 09:14:45-04:00,False,NaN,NaN,NaN,generate-epub.sh,ModificationType.MODIFY,1,1,NaN,NaN,NaN
522,7e8f93e57db6c016906121b9a868d1d767dd5edb,2022-07,Chetan Nair,93496359+ChetanNair@users.noreply.github.com,2022-07-31 12:44:43-04:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN

In [3]:
df.drop ( df[df.year_month == '2022-08'].index, inplace = True )
df

,commit_hash,year_month,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,976d90f37fc2a87eff4fba93db2db30788f67d83,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:08:55-08:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,1,0,NaN,NaN,NaN
1,ee6227a2a558281b37fe23ef1c627d5f95c331a6,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:09:37-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,5,0,NaN,NaN,NaN
2,0782047336cccd731281abe7605d5bf95496dadb,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:14:10-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,28,0,NaN,NaN,NaN
3,35f22bb85a40a94c657824919255ef13d25b7168,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:14:17-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,32,0,NaN,NaN,NaN
4,3bfedf4269c2c107a701d5dba8abe8f1d0d699d7,2017-02,Donne Martin,donne.martin@gmail.com,2017-02-26 05:14:17-08:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,14,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,79364dbbdcc305cf411719d0ea53345b5048d53c,2022-04,mleers,mleers4@gmail.com,2022-04-19 20:37:02-04:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN
519,7a094cec63795a3ebbaacebdf9dc4294cd3179b2,2022-04,Kian-Meng Ang,kianmeng.ang@gmail.com,2022-04-23 09:14:45-04:00,False,NaN,NaN,NaN,CONTRIBUTING.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN
520,7a094cec63795a3ebbaacebdf9dc4294cd3179b2,2022-04,Kian-Meng Ang,kianmeng.ang@gmail.com,2022-04-23 09:14:45-04:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN
521,7a094cec63795a3ebbaacebdf9dc4294cd3179b2,2022-04,Kian-Meng Ang,kianmeng.ang@gmail.com,2022-04-23 09:14:45-04:00,False,NaN,NaN,NaN,generate-epub.sh,ModificationType.MODIFY,1,1,NaN,NaN,NaN
522,7e8f93e57db6c016906121b9a868d1d767dd5edb,2022-07,Chetan Nair,93496359+ChetanNair@users.noreply.github.com,2022-07-31 12:44:43-04:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,1,1,NaN,NaN,NaN

In [4]:
grouped_df = df.groupby(['year_month']).agg({
    
    'commit_hash': 'nunique', 
    'file_lines_added': 'sum', 
    'file_lines_deleted': 'sum',
    'file_loc': 'sum',
    'file_complexity': 'sum',
    'file_token_count': 'sum',
    'dmm_unit_size': 'mean',
    'dmm_unit_complexity': 'mean',
    'dmm_unit_interfacing': 'mean'
} ).reset_index(level=[0])


grouped_df.rename(columns = {
    'commit_hash': 'commit_count',
    'file_lines_added': 'additions',
    'file_lines_deleted': 'deletions',
    'file_loc': 'agg_loc',
    'file_complexity': 'agg_complexity',
    'file_token_count': 'agg_token_count',
}, inplace = True)

grouped_df

,year_month,commit_count,additions,deletions,agg_loc,agg_complexity,agg_token_count,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing
0,2017-02,48,1238,18,0.0,0.0,0.0,NaN,NaN,NaN
1,2017-03,86,6291,706,692.0,192.0,4511.0,0.919958,0.908609,0.599393
2,2017-04,23,1840,29,0.0,0.0,0.0,NaN,NaN,NaN
3,2017-05,6,15,5,0.0,0.0,0.0,NaN,NaN,NaN
4,2017-06,2,3,2,0.0,0.0,0.0,NaN,NaN,NaN
5,2017-07,4,5,3,0.0,0.0,0.0,NaN,NaN,NaN
6,2017-08,1,0,0,0.0,0.0,0.0,NaN,NaN,NaN
7,2017-09,3,3,3,0.0,0.0,0.0,NaN,NaN,NaN
8,2017-10,3,3,2,0.0,0.0,0.0,NaN,NaN,NaN
9,2017-12,6,1794,7,0.0,0.0,0.0,NaN,NaN,NaN
10,2018-01,4,11,12,0.0,0.0,0.0,NaN,NaN,NaN
11,2018-02,6,1812,25,0.0,0.0,0.0,NaN,NaN,NaN
12,2018-03,8,110,69,674.0,218.0,4100.0,0.777778,0.777778,0.502315
13,2018-04,5,12,12,194.0,59.0,1246.0,NaN,NaN,0.000000
14,2018-05,3,8,4,209.0,62.0,1298.0,NaN,NaN,NaN
15,2018-06,2,3,3,0.0,0.0,0.0,NaN,NaN,NaN
16,2018-07,9,33,25,179.0,59.0,1151.0,NaN,NaN,NaN
17,2018-08,9,23,24,0.0,0.0,0.0,NaN,NaN,NaN
18,2018-09,7,13,13,0.0,0.0,0.0,NaN,NaN,NaN
19,2018-10,4,35,35,0.0,0.0,0.0,NaN,NaN,NaN
20,2018-11,1,1,1,0.0,0.0,0.0,NaN,NaN,NaN
21,2018-12,2,5,5,0.0,0.0,0.0,NaN,NaN,NaN
22,2019-01,2,2,2,0.0,0.0,0.0,NaN,NaN,NaN
23,2019-02,3,4,4,0.0,0.0,0.0,NaN,NaN,NaN
24,2019-03,2,2,2,0.0,0.0,0.0,NaN,NaN,NaN
25,2019-05,7,251,158,0.0,0.0,0.0,NaN,NaN,NaN
26,2019-06,1,331,1,0.0,0.0,0.0,NaN,NaN,NaN
27,2019-07,4,4,4,0.0,0.0,0.0,NaN,NaN,NaN
28,2019-08,6,7,7,0.0,0.0,0.0,NaN,NaN,NaN
29,2019-11,1,1,0,0.0,0.0,0.0,NaN,NaN,NaN
30,2019-12,3,13,13,85.0,27.0,597.0,NaN,NaN,NaN
31,2020-01,2,3,3,0.0,0.0,0.0,NaN,NaN,NaN
32,2020-03,3,5449,2934,0.0,0.0,0.0,NaN,NaN,NaN
33,2020-05,1,4,4,0.0,0.0,0.0,NaN,NaN,NaN
34,2020-07,27,400,201,0.0,0.0,0.0,NaN,NaN,NaN
35,2020-08,2,1,1,0.0,0.0,0.0,NaN,NaN,NaN
36,2020-10,1,2,2,0.0,0.0,0.0,NaN,NaN,NaN
37,2020-12,1,1,1,0.0,0.0,0.0,NaN,NaN,NaN
38,2021-01,1,4,4,0.0,0.0,0.0,NaN,NaN,NaN
39,2021-02,1,1,1,0.0,0.0,0.0,NaN,NaN,NaN
40,2021-05,1,1,1,0.0,0.0,0.0,NaN,NaN,NaN
41,2021-11,1,4,4,0.0,0.0,0.0,NaN,NaN,NaN
42,2022-02,1,4,4,0.0,0.0,0.0,NaN,NaN,NaN
43,2022-04,2,4,4,0.0,0.0,0.0,NaN,NaN,NaN
44,2022-07,1,1,1,0.0,0.0,0.0,NaN,NaN,NaN

In [5]:
grouped_df.to_csv ( f'datasets/{repo_name}_groupedby_yearmonth.csv', index = False )