In [1]:
import pandas as pd
import os
from get_repo_name import get_repo_name

repo_name = get_repo_name ( os.path.basename ( os.getcwd() ) )
dataset_path = f'datasets/{repo_name}_modfiles.csv'
df = pd.read_csv (dataset_path)
df.head()

,commit_hash,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,9d12a9c3f4ec059a3685c232ad179016fd35f909,vhf / victor felder,victorfelder@gmail.com,2013-10-10 23:50:37-07:00,False,NaN,NaN,NaN,LICENSE,ModificationType.ADD,24,0,NaN,NaN,NaN
1,9d12a9c3f4ec059a3685c232ad179016fd35f909,vhf / victor felder,victorfelder@gmail.com,2013-10-10 23:50:37-07:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,2,0,NaN,NaN,NaN
2,ee7b4d46e525096b26c1cc8f96a615751dc3ec48,vhf / victor felder,victorfelder@gmail.com,2013-10-11 08:53:59+02:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,563,0,NaN,NaN,NaN
3,023fa674cbe907b4de8210dbe8b563ffd3a151a4,vhf / victor felder,victorfelder@gmail.com,2013-10-11 08:59:11+02:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,3,2,NaN,NaN,NaN
4,6100b03a385ac9700558f6100414fa5d2178d09e,Victor Felder,victorfelder@gmail.com,2013-10-11 09:04:49+02:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,5,560,NaN,NaN,NaN

In [2]:
df.insert ( 1, 'year_month', pd.to_datetime(df['commit_datetime'], utc=True).dt.to_period('M') )
df.head()

G:\Anaconda3\lib\site-packages\pandas\core\arrays\datetimes.py:1101: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  warnings.warn(

,commit_hash,year_month,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count
0,9d12a9c3f4ec059a3685c232ad179016fd35f909,2013-10,vhf / victor felder,victorfelder@gmail.com,2013-10-10 23:50:37-07:00,False,NaN,NaN,NaN,LICENSE,ModificationType.ADD,24,0,NaN,NaN,NaN
1,9d12a9c3f4ec059a3685c232ad179016fd35f909,2013-10,vhf / victor felder,victorfelder@gmail.com,2013-10-10 23:50:37-07:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,2,0,NaN,NaN,NaN
2,ee7b4d46e525096b26c1cc8f96a615751dc3ec48,2013-10,vhf / victor felder,victorfelder@gmail.com,2013-10-11 08:53:59+02:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,563,0,NaN,NaN,NaN
3,023fa674cbe907b4de8210dbe8b563ffd3a151a4,2013-10,vhf / victor felder,victorfelder@gmail.com,2013-10-11 08:59:11+02:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,3,2,NaN,NaN,NaN
4,6100b03a385ac9700558f6100414fa5d2178d09e,2013-10,Victor Felder,victorfelder@gmail.com,2013-10-11 09:04:49+02:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,5,560,NaN,NaN,NaN

In [3]:
from analysis_lib import generate_ordinal_encoding_map

enc_map = generate_ordinal_encoding_map ( df["commit_author_email"] )
df["commit_author_enc"] = df["commit_author_email"].replace(enc_map)
df.head()

,commit_hash,year_month,commit_author_name,commit_author_email,commit_datetime,commit_merge,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing,file_name,file_change_type,file_lines_added,file_lines_deleted,file_loc,file_complexity,file_token_count,commit_author_enc
0,9d12a9c3f4ec059a3685c232ad179016fd35f909,2013-10,vhf / victor felder,victorfelder@gmail.com,2013-10-10 23:50:37-07:00,False,NaN,NaN,NaN,LICENSE,ModificationType.ADD,24,0,NaN,NaN,NaN,1
1,9d12a9c3f4ec059a3685c232ad179016fd35f909,2013-10,vhf / victor felder,victorfelder@gmail.com,2013-10-10 23:50:37-07:00,False,NaN,NaN,NaN,README.md,ModificationType.ADD,2,0,NaN,NaN,NaN,1
2,ee7b4d46e525096b26c1cc8f96a615751dc3ec48,2013-10,vhf / victor felder,victorfelder@gmail.com,2013-10-11 08:53:59+02:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,563,0,NaN,NaN,NaN,1
3,023fa674cbe907b4de8210dbe8b563ffd3a151a4,2013-10,vhf / victor felder,victorfelder@gmail.com,2013-10-11 08:59:11+02:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,3,2,NaN,NaN,NaN,1
4,6100b03a385ac9700558f6100414fa5d2178d09e,2013-10,Victor Felder,victorfelder@gmail.com,2013-10-11 09:04:49+02:00,False,NaN,NaN,NaN,README.md,ModificationType.MODIFY,5,560,NaN,NaN,NaN,1

In [4]:
df[df['commit_author_enc'] == 0].shape[0] # checking if there are any zeroes in author code

0

In [5]:
from analysis_lib import covid_ym

pre_df = df [ df['year_month'] < covid_ym ]
post_df = df [ df['year_month'] >= covid_ym ]

In [6]:
pre_df = pre_df.groupby(['commit_author_enc']).agg({
    
    'commit_hash': 'nunique', 
    'file_lines_added': 'sum', 
    'file_lines_deleted': 'sum',
    'file_loc': 'sum',
    'file_complexity': 'sum',
    'file_token_count': 'sum'
} ).reset_index(level=[0])

pre_df.rename(columns = {
     
    'commit_author_enc':'author_code',
    'commit_hash': 'commit_count',
    'file_lines_added': 'additions',
    'file_lines_deleted': 'deletions',
    'file_loc': 'agg_loc',
    'file_complexity': 'agg_complexity',
    'file_token_count': 'agg_token_count'
}, inplace = True)

pre_df

,author_code,commit_count,additions,deletions,agg_loc,agg_complexity,agg_token_count
0,1,236,4794,3863,0.0,0.0,0.0
1,2,1,1,1,0.0,0.0,0.0
2,3,1,0,2,0.0,0.0,0.0
3,4,1,1,1,0.0,0.0,0.0
4,5,1,1,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
1286,1287,1,1,0,0.0,0.0,0.0
1287,1288,1,1,0,0.0,0.0,0.0
1288,1289,1,9,1,0.0,0.0,0.0
1289,1290,1,1,0,0.0,0.0,0.0
1290,1291,1,1,0,0.0,0.0,0.0

In [7]:
post_df = post_df.groupby(['commit_author_enc']).agg({
    
    'commit_hash': 'nunique', 
    'file_lines_added': 'sum', 
    'file_lines_deleted': 'sum',
    'file_loc': 'sum',
    'file_complexity': 'sum',
    'file_token_count': 'sum'
} ).reset_index(level=[0])

post_df.rename(columns = {
     
    'commit_author_enc':'author_code',
    'commit_hash': 'commit_count',
    'file_lines_added': 'additions',
    'file_lines_deleted': 'deletions',
    'file_loc': 'agg_loc',
    'file_complexity': 'agg_complexity',
    'file_token_count': 'agg_token_count'
}, inplace = True)

post_df

,author_code,commit_count,additions,deletions,agg_loc,agg_complexity,agg_token_count
0,146,7,81,52,0.0,0.0,0.0
1,278,1,6,12,0.0,0.0,0.0
2,328,1,1,1,0.0,0.0,0.0
3,492,39,2024,1590,0.0,0.0,0.0
4,747,3,8,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
949,2217,1,14,0,0.0,0.0,0.0
950,2218,1,3,0,0.0,0.0,0.0
951,2219,1,15,0,0.0,0.0,0.0
952,2220,1,8,0,0.0,0.0,0.0
953,2221,1,7,1,0.0,0.0,0.0

In [8]:
from analysis_lib import calc_and_compare_means

calc_and_compare_means ( pre_df, post_df )

Pre and Post-Covid Mean Comparisons:
commit count :  3  vs  2  ->  Down (33.3%)
additions :  22  vs  20  ->  Down (9.1%)
deletions :  15  vs  8  ->  Down (46.7%)
agg loc :  0  vs  0  ->  No change
agg complexity :  0  vs  0  ->  No change
agg token count :  0  vs  0  ->  No change

In [9]:
from analysis_lib import get_equilibrium_pc

print("Pre-pandemic equilibrium percentages:")
for idx in range ( 1, 7 ):
    print ( f'{pre_df.columns[idx]} = { get_equilibrium_pc ( list ( pre_df[pre_df.columns[idx]] ) ) }' )
    
print("\nPost-pandemic equilibrium percentages:")
for idx in range ( 1, 7 ):
    print ( f'{post_df.columns[idx]} = { get_equilibrium_pc ( list ( post_df[post_df.columns[idx]] ) ) }' )

Pre-pandemic equilibrium percentages:
commit_count = 7.0
additions = 0.9
deletions = 0.4
agg_loc = 0.1
agg_complexity = 0.1
agg_token_count = 0.1

Post-pandemic equilibrium percentages:
commit_count = 15.1
additions = 1.2
deletions = 0.2
agg_loc = 0.1
agg_complexity = 0.1
agg_token_count = 0.1

In [10]:
from analysis_lib import get_pareto_pc

print("Pre-pandemic pareto percentages:")
for idx in range ( 1, 7 ):
    print ( f'{pre_df.columns[idx]} = { get_pareto_pc ( list ( pre_df[pre_df.columns[idx]] ) ) }' )
    
print("\nPost-pandemic pareto percentages:")
for idx in range ( 1, 7 ):
    print ( f'{post_df.columns[idx]} = { get_pareto_pc ( list ( post_df[post_df.columns[idx]] ) ) }' )

Pre-pandemic pareto percentages:
commit_count = 44.1
additions = 6.0
deletions = 1.5
agg_loc = 0.1
agg_complexity = 0.1
agg_token_count = 0.1

Post-pandemic pareto percentages:
commit_count = 59.0
additions = 10.8
deletions = 2.3
agg_loc = 0.1
agg_complexity = 0.1
agg_token_count = 0.1