In [1]:
import pandas as pd
import os
from get_repo_name import get_repo_name

repo_name = get_repo_name ( os.path.basename ( os.getcwd() ) )
dataset_path = f'datasets/{repo_name}_final.csv'
df = pd.read_csv (dataset_path)
df

,year_month,commit_count,additions,deletions,agg_loc,agg_complexity,agg_token_count,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing
0,2013-05,53,43952,523,25918.0,10225.0,251334.0,0.582596,0.742723,0.821696
1,2013-06,213,11390,28035,61790.0,11686.0,358919.0,0.515204,0.578879,0.582611
2,2013-07,205,58995,55867,45952.0,13751.0,349160.0,0.502664,0.555284,0.588020
3,2013-08,53,2784,2284,9986.0,1908.0,57123.0,0.606317,0.576510,0.640145
4,2013-09,75,5394,1966,16589.0,2762.0,93146.0,0.545374,0.734521,0.787510
...,...,...,...,...,...,...,...,...,...,...
106,2022-03,78,11142,15013,299747.0,19363.0,1255587.0,0.528100,0.765604,0.852136
107,2022-04,82,14481,6267,374268.0,13718.0,1439473.0,0.532105,0.631447,0.598118
108,2022-05,51,6067,2013,130354.0,7434.0,526962.0,0.493065,0.887337,0.936656
109,2022-06,66,9384,3963,344830.0,15783.0,1343876.0,0.522034,0.636599,0.676099
110,2022-07,42,7953,6772,255431.0,7296.0,980495.0,0.509717,0.723127,0.640245

In [2]:
# df['year_month'] = pd.to_datetime(df['year_month'])
df = df.set_index(df['year_month'])
df

,year_month,commit_count,additions,deletions,agg_loc,agg_complexity,agg_token_count,dmm_unit_size,dmm_unit_complexity,dmm_unit_interfacing
year_month,,,,,,,,,,
2013-05,2013-05,53,43952,523,25918.0,10225.0,251334.0,0.582596,0.742723,0.821696
2013-06,2013-06,213,11390,28035,61790.0,11686.0,358919.0,0.515204,0.578879,0.582611
2013-07,2013-07,205,58995,55867,45952.0,13751.0,349160.0,0.502664,0.555284,0.588020
2013-08,2013-08,53,2784,2284,9986.0,1908.0,57123.0,0.606317,0.576510,0.640145
2013-09,2013-09,75,5394,1966,16589.0,2762.0,93146.0,0.545374,0.734521,0.787510
...,...,...,...,...,...,...,...,...,...,...
2022-03,2022-03,78,11142,15013,299747.0,19363.0,1255587.0,0.528100,0.765604,0.852136
2022-04,2022-04,82,14481,6267,374268.0,13718.0,1439473.0,0.532105,0.631447,0.598118
2022-05,2022-05,51,6067,2013,130354.0,7434.0,526962.0,0.493065,0.887337,0.936656
2022-06,2022-06,66,9384,3963,344830.0,15783.0,1343876.0,0.522034,0.636599,0.676099
2022-07,2022-07,42,7953,6772,255431.0,7296.0,980495.0,0.509717,0.723127,0.640245

In [3]:
pre_covid_ym = '2020-02'
covid_ym = '2020-03'
df1 = df [ str(df.year_month[0]) : pre_covid_ym ]
df2 = df [ covid_ym: str(df.year_month[-1]) ]
df1 = df1.reset_index ( drop = True )
df2 = df2.reset_index ( drop = True )

df1.shape, df2.shape

((82, 10), (29, 10))

In [4]:
from top_contributors import get_equilibrium_pc, get_pareto_pc

print("Pre-pandemic equilibrium percentages:")
for idx in range ( 1, len(df1.columns) ):
    print ( f'{df1.columns[idx]} = { get_equilibrium_pc ( list ( df1[df1.columns[idx]] ) ) }' )

Pre-pandemic equilibrium percentages:
commit_count = 34
additions = 19
deletions = 16
agg_loc = 23
agg_complexity = 29
agg_token_count = 24
dmm_unit_size = 45
dmm_unit_complexity = 43
dmm_unit_interfacing = 43

In [5]:
print("Post-pandemic equilibrium percentages:")
for idx in range ( 1, len(df2.columns) ):
    print ( f'{df2.columns[idx]} = { get_equilibrium_pc ( list ( df2[df2.columns[idx]] ) ) }' )

Post-pandemic equilibrium percentages:
commit_count = 37
additions = 30
deletions = 27
agg_loc = 37
agg_complexity = 33
agg_token_count = 37
dmm_unit_size = 47
dmm_unit_complexity = 47
dmm_unit_interfacing = 47

In [6]:
print("Pre-pandemic Pareto percentages:")
for idx in range ( 1, len(df1.columns) ):
    print ( f'{df1.columns[idx]} = { get_pareto_pc ( list ( df1[df1.columns[idx]] ) ) }' )

Pre-pandemic Pareto percentages:
commit_count = 66
additions = 43
deletions = 39
agg_loc = 49
agg_complexity = 58
agg_token_count = 53
dmm_unit_size = 75
dmm_unit_complexity = 73
dmm_unit_interfacing = 73

In [7]:
print("Post-pandemic Pareto percentages:")
for idx in range ( 1, len(df2.columns) ):
    print ( f'{df2.columns[idx]} = { get_pareto_pc ( list ( df2[df2.columns[idx]] ) ) }' )

Post-pandemic Pareto percentages:
commit_count = 70
additions = 60
deletions = 57
agg_loc = 67
agg_complexity = 67
agg_token_count = 67
dmm_unit_size = 77
dmm_unit_complexity = 77
dmm_unit_interfacing = 77